### ISSUE TITLE
Add "dev" branch for experimental features

### ISSUE THREAD

**Issue by frost19k** [cybersecsi/RAUDI#20]
Hello

I have ported `raudi.py` to `python_on_whales`. 

This allows for Buildkit builds - enabling much more complex Dockerfiles.

However, I feel it would be better to make a PR to a dev branch - in case something is not working correctly. 

https://user-images.githubusercontent.com/49780407/149234725-f955e0fe-b697-479b-9e90-2a5ec31c3789.mp4

**Comment by thelicato** [comment]
Hello!
Unfortunately we work at different hours and there is a little bit of delay u.u
BTW I really like thus ``python-on-whales``. We created a develop branch so that you can make the PR.

A couple days ago I made a huge mistake with the git history and now everyone that forked before has a messed up history. So in order to avoid a broken merge you should fork again the repo. I'm really sorry for this.
Won't happen again.

**Comment by frost19k** [comment]
That's true, but it's only 4.5 hours - I think. I was just up way too early today.

You did mention you were interested in porting it - which is why I did it for you. I wouldn't do something so drastic without the maintainer's willingness.

No worries, I've made a fresh fork. I'm just getting the PR ready... :-)
